// Generated by CoffeeScript 1.3.3
(function() {

  this.Calculator = (function() {

    function Calculator() {}

    Calculator.prototype.add = function(x, y) {
      return x + y;
    };

    Calculator.prototype.subtract = function(x, y) {
      return x - y;
    };

    Calculator.prototype.multiply = function(x, y) {
      return x * y;
    };

    Calculator.prototype.divide = function(x, y) {
      return x / y;
    };

    return Calculator;

  })();

}).call(this);
