// Generated by CoffeeScript 1.3.3
(function() {

  describe('Calculator', function() {
    var calculator;
    calculator = null;
    beforeEach(function() {
      return calculator = new Calculator();
    });
    it('can add two numbers', function() {
      var result;
      result = calculator.add(2, 3);
      return expect(result).toBe(5);
    });
    it('can subtract two numbers', function() {
      var result;
      result = calculator.subtract(5, 3);
      return expect(result).toBe(2);
    });
    it('can multiply two numbers', function() {
      var result;
      result = calculator.multiply(3, 4);
      return expect(result).toBe(12);
    });
    return it('can divide two numbrs', function() {
      var result;
      result = calculator.divide(12, 4);
      return expect(result).toBe(3);
    });
  });

}).call(this);
